imports:
    - php
filter:
    paths: [src/*]
tools:
    php_code_coverage: true
    php_sim:
        min_mass: 30 # Defaults to 16
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'
    dependencies:
        before:
            - composer install --prefer-source
