language: php

sudo: required
dist: trusty
group: edge

php:
  - 7.0
  - 7.1
  - nightly
  
matrix:
  allow_failures:
    - php: nightly

install: composer install

script: vendor/bin/phpunit tests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f0abd75c9ea61d414afa
    on_success: always
    on_failure: always
    on_start: false
