language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

install: composer install

script: phpunit --configuration phpunit.xml.dist

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
